/**
 * Renders results/examples-results.json into EXAMPLES-REPORT.md tables.
 *
 *   node examples-sweep/report.mjs
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const _dirname = path.dirname(fileURLToPath(import.meta.url));
const results = JSON.parse(
  fs.readFileSync(path.resolve(_dirname, '../results/examples-results.json'), 'utf8'),
);

const byExample = new Map();
for (const r of results) {
  if (!byExample.has(r.example)) byExample.set(r.example, {});
  byExample.get(r.example)[r.cfg] = r;
}

const kb = (n) => `${(n / 1024).toFixed(1)}`;
const ms = (n) => n.toFixed(1);
const pct = (from, to) =>
  from > 0 ? `${(((to - from) / from) * 100).toFixed(0)}%` : '—';

function line(cols) {
  return `| ${cols.join(' | ')} |`;
}

const out = [];
out.push('<!-- generated by examples-sweep/report.mjs -->');

for (const flavor of ['Device', '']) {
  const F = (r) => flavor === 'Device' ? r.fcpDeviceMs : r.fcpMs;
  const T = (r) => flavor === 'Device' ? r.ttiDeviceMs : r.ttiMs;
  for (const mode of ['jitless', 'v8']) {
    out.push(`\n### First-frame timings (ms) — ${mode}${
      flavor === 'Device'
        ? ', bytecode-precompile proxy (MT parse excluded, as on devices)'
        : ', raw (includes MT parse — web-platform-like)'
    }\n`);
    out.push(line(['example', 'FCP off', 'FCP ifr', 'ΔFCP', 'FCP ifr+et', 'TTI off', 'TTI ifr', 'ΔTTI', 'TTI ifr+et', 'nodes']));
    out.push(line(Array(10).fill('---')));
    for (const [example, cfgs] of [...byExample.entries()].sort()) {
      const o = cfgs.off?.[mode];
      const i = cfgs.ifr?.[mode];
      const e = cfgs['ifr-et']?.[mode];
      if (!o || !i) {
        out.push(line([example, ...Array(8).fill('n/a'), '']));
        continue;
      }
      out.push(line([
        example,
        ms(F(o)), ms(F(i)), pct(F(o), F(i)), e ? ms(F(e)) : 'n/a',
        ms(T(o)), ms(T(i)), pct(T(o), T(i)), e ? ms(T(e)) : 'n/a',
        String(o.contentFinal),
      ]));
    }
  }
}

out.push('\n### Bundle size (main.lynx.bundle, KiB) and protocol payload\n');
out.push(line(['example', 'raw off', 'raw ifr', 'Δraw', 'gz off', 'gz ifr', 'Δgz', 'gz ifr+et', 'MT off→ifr (KiB)', '1st batch off (KiB)', 'doc ✓']));
out.push(line(Array(11).fill('---')));
for (const [example, cfgs] of [...byExample.entries()].sort()) {
  const o = cfgs.off;
  const i = cfgs.ifr;
  const e = cfgs['ifr-et'];
  if (!o || !i) {
    out.push(line([example, ...Array(10).fill('n/a')]));
    continue;
  }
  out.push(line([
    example,
    kb(o.lynxRaw), kb(i.lynxRaw), pct(o.lynxRaw, i.lynxRaw),
    kb(o.lynxGz), kb(i.lynxGz), pct(o.lynxGz, i.lynxGz),
    e ? kb(e.lynxGz) : 'n/a',
    `${kb(o.mtBytes)}→${kb(i.mtBytes)}`,
    o.v8 ? kb(o.v8.firstBatchBytes) : '?',
    `${i.docMatchesOff ? '✓' : '✗'}${e ? (e.docMatchesOff ? '✓' : '✗') : ''}`,
  ]));
}

// Headline medians.
const deltas = { fcp: [], tti: [], gz: [], fcpEt: [], ttiEt: [] };
for (const [, cfgs] of byExample) {
  const o = cfgs.off?.jitless;
  const i = cfgs.ifr?.jitless;
  const e = cfgs['ifr-et']?.jitless;
  if (o && i) {
    deltas.fcp.push(i.fcpDeviceMs / o.fcpDeviceMs);
    deltas.tti.push(i.ttiDeviceMs / o.ttiDeviceMs);
    deltas.gz.push(cfgs.ifr.lynxGz / cfgs.off.lynxGz);
  }
  if (o && e) {
    deltas.fcpEt.push(e.fcpDeviceMs / o.fcpDeviceMs);
    deltas.ttiEt.push(e.ttiDeviceMs / o.ttiDeviceMs);
  }
}
const med = (xs) => {
  const s = [...xs].sort((a, b) => a - b);
  return s[Math.floor(s.length / 2)];
};
out.unshift(
  `\n**Medians across examples (jitless, device proxy):** FCP ×${
    med(deltas.fcp).toFixed(2)
  } (ifr) / ×${med(deltas.fcpEt).toFixed(2)} (ifr+et), TTI ×${
    med(deltas.tti).toFixed(2)
  } (ifr) / ×${med(deltas.ttiEt).toFixed(2)} (ifr+et), lynx.bundle gz ×${
    med(deltas.gz).toFixed(2)
  }\n`,
);

fs.writeFileSync(path.resolve(_dirname, 'TABLES.md'), out.join('\n'));
console.log(out.join('\n'));
